# From: https://dev.to/andresfmoya/install-jenkins-using-docker-compose-4cab
# Use: docker-compose up -d
# Get password: ❯ docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword

version: "2"

services:
  jenkins:
    container_name: jenkins
    build: .
    env_file:
      - ./.env
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
