# All-in-one docker-compose file for all sub-files
# Docs: 
#   Extending docker-compose: https://docs.docker.com/compose/extends/
#   Networking: https://runnable.com/docker/docker-compose-networking
# docker-compose up -d keeps it running
# I can access bash using: docker exec -i -t ubuntu-ext bash

version: "3"


services:
  sql-server-db:
    container_name: sql-server-db-ext
    networks:
      dbt-network:
        ipv4_address: 172.23.0.2
    extends:
      file: ./sqlserver/docker-compose.yml
      service: sql-server-db

  ubuntu:
    container_name: ubuntu-ext
    networks:
      dbt-network:
        ipv4_address: 172.23.0.3
    extends:
      file: ./ubuntu/docker-compose.yml
      service: ubuntu

  jenkins:
    container_name: jenkins-ext
    networks:
      dbt-network:
        ipv4_address: 172.23.0.4
    extends:
      file: ./jenkins/docker-compose.yml
      service: jenkins


networks:
  dbt-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
