# example profiles.yml file

config:
  send_anonymous_usage_stats: true

sqlserver_demo:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      host: 172.23.0.2
      user: sa
      pass: Secure1337Password
      port: 1433
      database: Import
      schema: dbo
      threads: 4
    prod:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      host: 172.23.0.2
      user: not_sa
      pass: super_secret_password
      port: 1433
      database: Common
      schema: dbo
      threads: 4
