# example profiles.yml file

sqlserver_demo:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      host: 172.23.0.2
      user: sa
      pass: Secure1337Password
      port: 1433
      database: Import
      schema: dbo
      threads: 4
