## To run: docker-compose run -d

version: "2"

services:

  sql-server-db:
    container_name: sql-server-db
    build: .
    volumes:
      - ./volumes:/var/opt/mssql/data
    ports:
      - "1433:1433"
