## To run: docker-compose run -d

version: "3"

services:

  sql-server-db:
    container_name: sql-server-db
    build: .
    volumes:
      - ~/git/dbt-demo/containers/sqlserver/volumes:/var/opt/mssql/data
    ports:
      - "1433:1433"
